# Generated by Django 3.2.12 on 2022-03-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.TextField(db_column='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('created_at', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('release_date', models.DateField(db_column='ReleaseDate')),
                ('description', models.TextField(db_column='Description')),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='quiz.categories')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.images'),
        ),
    ]
