# Generated by Django 3.2.12 on 2022-03-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='images',
            name='filename',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.images'),
        ),
    ]
