# Generated by Django 3.2.12 on 2022-03-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20220327_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='filename',
            new_name='name',
        ),
    ]
