name: quiz.Backend deploy

on:
  push:
    branches: [master]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mbcodepl/mcms:quizybackend

  deploy:
    name: Deploy to server
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOMEHOST }}
          USERNAME: ${{ secrets.HOMEUSERNAME }}
          PORT: ${{ secrets.HOMEPORT }}
          KEY: ${{ secrets.HOMESSHKEY }}
          script: |
            docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull mbcodepl/mcms:quizybackend
            docker container stop $(docker container ls -q --filter name=quizybackend_*)
            docker run -d --restart unless-stopped --name quizybackend_${{ github.run_id }} -p 6002:6002 \
            -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
            -e DATABASE_USER="${{ secrets.DATABASE_USER }}" \
            -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
            -e DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
            -e DATABASE_PORT="${{ secrets.DATABASE_PORT }}" \
            mbcodepl/mcms:quizybackend